name: Terraform

on:
  push:
    branches: [main]
    paths: ["infrastructure/terraform/**"]
  pull_request:
    branches: [main]
    paths: ["infrastructure/terraform/**"]

permissions:
  id-token: write
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: infrastructure/terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform fmt -check
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -var-file=environments/dev/terraform.tfvars
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var-file=environments/dev/terraform.tfvars
